export const CREATE_TODO_SUCCESSFUL = "CREATE_TODO_SUCCESSFUL";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";
export const CREATE_TODO = "CREATE_TODO";

export const GET_ALL_TODO = "GET_ALL_TODO";
export const GET_ALL_TODO_SUCESSFUL = "GET_ALL_TODO_SUCESSFUL";
export const GET_ALL_TODO_FAILURE= "GET_ALL_TODO_FAILURE";

export const DELETE_TODO = "DELETE_TODO";
export const DELETE_TODO_SUCESSFUL = "DELETE_TODO_SUCESSFUL";
export const DELETE_TODO_FAILURE= "DELETE_TODO_FAILURE";